version: "3.04"
services:
  appmysql:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - master-network
  myapp:
    image: andoliver46/projetos-myapp:latest
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    depends_on:
      - appmysql
    networks:
      - master-network
networks:
  master-network:
    driver: bridge